server:
  port: 8080
spring:
  profiles:
    active: DEVELOP
  flyway:
    baseline-on-migrate: true
  datasource:
    tasks:
      jdbc-url: jdbc:postgresql://localhost:5432/eisetasks
      username: someuser
      password: somepass
      driver-class-name: org.postgresql.Driver

jwt:
  issuer: 'some.admin@mail.net'
  signingKey: 'sZcps3y00xnFgpKs8rgoc6lri8uL4mqb1hJ'
  aTokenDuration: 30

configuration:
  meta:
    status: inbox
    order: desc
    start-page: 1
    page-size: 25
    min-page-size: 10
    max-page-size: 50

logging:
  path: log
  file: app_logs.log

app:
  name: 'todo-taskmanager'